### ISSUE TITLE
Documentation changes for ResInsight 09.2020

### ISSUE THREAD

**Issue by magnesj** [OPM/ResInsight-UserDocumentation#11]
## Surfaces

- [ ] Export of surface from k-layer Eclipse https://github.com/OPM/ResInsight/issues/5957
- [ ] RImport of surface with results, document how to select results 
- [ ] Reload of surface https://github.com/OPM/ResInsight/issues/6268

## Geomech derived results
These derived results must be documented both by screenshots of property editor and detailed description by formulas.

- [ ] Calculation of stress when biot factor is less than one
- [ ] Permeability
- [ ] Pore compressibility https://github.com/OPM/ResInsight/issues/6031
- [ ] Stress anisotropy
- [ ] Mud window calculations https://github.com/OPM/ResInsight/issues/6213
- [ ] Renaming https://github.com/OPM/ResInsight/issues/6032

**Comment by kriben** [comment]
See #14 for description of the formulas.
